shfmt

diff --git a/.local/bin/compress b/.local/bin/compress
--- a/.local/bin/compress
+++ b/.local/bin/compress
@@ -4,27 +4,27 @@
 cLevel="3"
 PARAMS=""
 while (("$#")); do
-    case "$1" in
-    -cl | --compression-level)
-        cLevel=$2
-        shift 2
-        ;;
-    --) # end argument parsing
-        shift
-        break
-        ;;
-    -*) # unsupported flags
-        echo "Error: Unsupported flag $1" >&2
-        exit 1
-        ;;
-    *) # preserve positional arguments
-        PARAMS+="$1"
-        shift
-        ;;
-    esac
+  case "$1" in
+  -cl | --compression-level)
+    cLevel=$2
+    shift 2
+    ;;
+  --) # end argument parsing
+    shift
+    break
+    ;;
+  -*) # unsupported flags
+    echo "Error: Unsupported flag $1" >&2
+    exit 1
+    ;;
+  *) # preserve positional arguments
+    PARAMS+="$1"
+    shift
+    ;;
+  esac
 done
 # set positional arguments in their proper place
 eval set -- "$PARAMS"
 
-tar -cvf archive.tar "$PARAMS" && \
-    zstd -z --rm -"$cLevel" -T"$(nproc)" archive.tar -o archive.tar.zstd
+tar -cvf archive.tar "$PARAMS" &&
+  zstd -z --rm -"$cLevel" -T"$(nproc)" archive.tar -o archive.tar.zstd
